### ISSUE TITLE
Test Documentation - Mike

### ISSUE THREAD

**Issue by brawblan** [Devslopes-Herd/TeamStandardsAndRules#9]
## Action
- As an experienced team member, I will walk through the steps/tasks provided to join this organization to troubleshoot any potential issues that I believe a less experienced developer may face.

## Acceptance Criteria
- I have read the README.md
- I have read the RULES.md
- I have read the STANDARDS.md
- I have completed all tasks required in the file listed above
- I have noted any problems in the process and created a new Issue for each problem found.

**Comment by mikesz88** [comment]
- Task 4 could seem confusing because of not needing to do the last line of Definition of Ready Check.
- The line of browsers still felt confusing. So you want it to work on a live server  AND other browsers like chrome and safari? Or live server and another browser are fine? 
- I have completed all tasks and waiting for you to confirm PR for me to finish the last task. That is a good way for them to acknowledge they read the rules and proof they can contribute.

**Comment by brawblan** [comment]
Thanks for the feedback! I'll get on that later.
I just sent you a Discord message. I'm hoping this can become something really big!
